### PR TITLE
fix(python): fix error with optional dependencies in pyproject.toml

### LINKED ISSUE #3720: pyproject.toml toml decode error on optional dependency
## Description

Trivy filesystem scan doesn't work anymore on my project after the update to 0.38.0.

## What did you expect to happen?

It should report vulnerabilities as before.

## What happened instead?

The tool reports a failure.

## Output of run with `-debug`:

```
FATAL	filesystem scan error: scan error: scan failed: failed analysis: post analysis error: post analysis error: poetry walk error: unable to parse pyproject.toml: toml decode error: toml: line 46 (last key "tool.poetry.dependencies.foo"): incompatible types: TOML value has type map[string]interface {}; destination has type string
```

Line 46 of my `pyproject.toml` file is an optional dependency:

```
foo = {version = "0.1.0", optional = true}
```

## Output of `trivy -v`:

```
0.38.0
```

## Additional details (base image name, container registry info...):

public.ecr.aws/aquasecurity/trivy:latest

### PR DESCRIPTION
**Pull request by ilpianista**
## Description

This fixes optional dependencies support in `pyproject.toml` once aquasecurity/go-dep-parser#182 is merged (`go.mod` should be updated as well - marked as draft because of that).

## Related issues
- Close #3720

## Related PRs
- [x] aquasecurity/go-dep-parser#182

Remove this section if you don't have related PRs.

## Checklist
- [x] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [x] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [x] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Review by DmitriyLewen — CHANGES_REQUESTED** [review]
@ilpianista 
Thanks for your work!

Can you update `go-dep-parser` version? 
Please use [commit for your PR](https://github.com/aquasecurity/go-dep-parser/commit/e4068021315b19bd070a34ca199a346280064715).

And 1 more moment:
we are using rules for PR title - https://aquasecurity.github.io/trivy/v0.38/community/contribute/pr/
can you update title of this PR?

**Comment by DmitriyLewen** [comment]
Hello @ilpianista 
Thank you again for your contribution!

I made the necessary changes because today we want to release v0.38.1.

Regards, Dmitriy

**Comment by ilpianista** [comment]
> I made the necessary changes because today we want to release v0.38.1.

Ops, I lost this comment and force-pushed :innocent:

**Comment by DmitriyLewen** [comment]
Happens
Can you update `go-dep-parser` and get the latest changes from main branch?

**Comment by DmitriyLewen** [comment]
Remove the [rekor version change](https://github.com/aquasecurity/trivy/pull/3741/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R66) (we don't know why golang does this) and resolve the conflict please

**Review by DmitriyLewen — APPROVED** [review]
LGTM. Thanks for your work!

**Comment by ilpianista** [comment]
@DmitriyLewen done

**Review by knqyf263 — APPROVED** [review]
