### ISSUE TITLE
pyproject.toml toml decode error on optional dependency

### ISSUE THREAD

**Issue by ilpianista** [aquasecurity/trivy#3720]
## Description

Trivy filesystem scan doesn't work anymore on my project after the update to 0.38.0.

## What did you expect to happen?

It should report vulnerabilities as before.

## What happened instead?

The tool reports a failure.

## Output of run with `-debug`:

```
FATAL	filesystem scan error: scan error: scan failed: failed analysis: post analysis error: post analysis error: poetry walk error: unable to parse pyproject.toml: toml decode error: toml: line 46 (last key "tool.poetry.dependencies.foo"): incompatible types: TOML value has type map[string]interface {}; destination has type string
```

Line 46 of my `pyproject.toml` file is an optional dependency:

```
foo = {version = "0.1.0", optional = true}
```

## Output of `trivy -v`:

```
0.38.0
```

## Additional details (base image name, container registry info...):

public.ecr.aws/aquasecurity/trivy:latest

**Comment by knqyf263** [comment]
@DmitriyLewen Could you prioritize this issue?

**Comment by knqyf263** [comment]
Please try v0.38.1

**Comment by sidmitra** [comment]
Can confirm. Works now! 

`brew upgrade trivy` picked up the release.
